### ISSUE TITLE
Add logos for other technologies

### ISSUE THREAD

**Issue by Gillespie59** [T3kstiil3/teacher_toolkit#5]
- VueJS (.vue)
- TypeScript (.ts)
- Java (.java)
- Kotlin (.kt)
- Golang (.go)

**Comment by T3kstiil3** [comment]
![image](https://user-images.githubusercontent.com/3717296/36232471-314fea2a-11e2-11e8-9279-33cc494d0854.png)
![image](https://media.giphy.com/media/3o6vY1AxCgaUkWC6sM/source.gif)

**Comment by T3kstiil3** [comment]
[ee1dd8ebf41e968d](https://github.com/T3kstiil3/teacher_toolkit/commit/ee1dd8ebf41e968d969c0b8bb4e05055e4fcf448)
